# Generated by Django 3.2.6 on 2021-08-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapfriend',
            name='living',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
